[pytest]
pythonpath = tests
# Run Backend
addopts =  -ra -q --alluredir=allure-results --browser chromium --video=on --headed --slowmo 500 --reruns 1 --reruns-delay 2
#addopts =  -ra -q --alluredir=allure-results --browser chromium --reruns 1 --reruns-delay 2
filterwarnings =
    ignore:.*getdata.*:DeprecationWarning
log_cli = true
timeout = 300
markers =
    backend: Backend regress
    frontend: Frontend regress
    dependency: pytest-dependency marker

# Run Chrome with UI (chromium/ webkit)
#https://stepik.org/lesson/826369/step/1?unit=829902
;addopts =  --headed --alluredir=./logs/allure-result --browser chromium --slowmo 1000 --video=on
;addopts =   --headed --slowmo 1000 --video=on
;--headed --browser webkit --browser chromium --device="iPhone 13 Mini"
;--video on --screenshot on-failure --video=on --device="iPhone 13" --browser webkit
